services:
  vela:
    container_name: vela
    ports:
      - 61106:80
    volumes:
      - ~/Desktop/docker/universe/vela/dist/:/usr/share/nginx/html/
      - ~/Desktop/docker/universe/vela/default.conf:/etc/nginx/conf.d/default.conf
    image: nginx
